
server:
  servlet:
    context-path: /flightbooking/api/v1/



spring:
  profiles:
    active: prod
    include:
      - swagger
  jackson:
    serialization:
      indent-output: true
    deserialization:


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/flightbookingapp?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:finartz}
  cache:
    ehcache:
      config: classpath:ehcache.xml


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    open-in-view : false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.generate_statistics: false
      hibernate:jdbc.time_zone: UTC
      cache:
        ehcache:
          missing_cache_strategy: create



